### PR TITLE
ec fix for search_path with std::filesystem.

### LINKED ISSUE #287: Implementation of BOOST_PROCESS_USE_STD_FS incomplete
In https://github.com/boostorg/process/blob/boost-1.80.0/include/boost/process/detail/posix/search_path.hpp#L30

```
        boost::system::error_code ec;
        bool file = boost::process::filesystem::is_regular_file(p, ec);
```
With `BOOST_PROCESS_USE_STD_FS` defined, compilation fails due to a mismatch of the error_code parameter:
```
no known conversion for argument 2 from 'boost::system::error_code' to 'std::error_code&'
  257 |   is_regular_file(const path& __p, error_code& __ec) noexcept
      |                                    ~~~~~~~~~~~~^~~~
```

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
closes #287.

### CODE REVIEW

File: include/boost/process/detail/posix/search_path.hpp [hunk 1]
```diff
@@ -27,7 +27,11 @@ inline boost::process::filesystem::path search_path(
     for (const boost::process::filesystem::path & pp : path)
     {
         auto p = pp / filename;
+#if defiend(BOOST_PROCESS_USE_STD_FS)
```
Comment (stuomas) [inline include/boost/process/detail/posix/search_path.hpp:30]: typo defiend -> defined

File: include/boost/process/detail/windows/search_path.hpp [hunk 2]
```diff
@@ -61,7 +61,11 @@ inline boost::process::filesystem::path search_path(
         {
             boost::process::filesystem::path pp_ext = p;
             pp_ext += ext;
+#if defiend(BOOST_PROCESS_USE_STD_FS)
```
Comment (stuomas) [inline include/boost/process/detail/windows/search_path.hpp:64]: typo defiend -> defined
